#!/usr/bin/bash
set -e

TRASH=~/Trash

if [[ ! -d "$TRASH" ]]
then
        mkdir -p "$TRASH"
fi


restore(){
        FILE="$(basename "$1")"
        mv -v "$TRASH/${FILE%.trashinfo}" "$(cat $TRASH/$FILE)"
        rm "$TRASH/$FILE"
}

list(){
        exa -l "$TRASH"
}

empty(){
        rm -rfv "$TRASH"/*
}

size(){
        du -sh "$TRASH"
}

trash(){
        for file in "$@"
        do
                NAME="$(basename "$file")"
                realpath "$file" > "$TRASH/${NAME%/}.trashinfo"
                mv "$file" "$TRASH"
        done
}


while [[ -n "$1" ]]
do
        case "$1" in
                r | restore)
                        shift
                        restore "$1"
                        exit
                        ;;
                l | list)
                        shift
                        list
                        exit
                        ;;
                e | empty)
                        empty
                        exit
                        ;;
                s | size)
                        size
                        exit
                        ;;
                *)
                        trash "$@"
                        exit
                        ;;
        esac
        shift
done
